title: "Simulation Portfolio"
description: "A showcase of simulation demos and technology samples."
baseurl: "/pabloinigoblasco" 
url:  "https://pabloinigoblasco.github.io"
theme: jekyll-theme-cayman 
