title: "Simulation Portfolio"
description: "A showcase of simulation demos and technology samples."
baseurl: "/pabloinigoblasco" 
url:  "https://pabloinigoblasco.github.io"
#theme: jekyll-theme-cayman 
#theme: jekyll-theme-minimal
#theme: jekyll-theme-midnight
theme: jekyll-theme-architect
#theme: jekyll-theme-slate

# markdown: kramdown
# plugins:
#   - jekyll-seo-tag
