title: "Simulation Portfolio"
description: "A showcase of simulation demos and technology samples."
baseurl: "/pabloinigoblasco-simulation-portfolio" 
url:  "https://pabloinigoblasco.github.io"
theme: jekyll-theme-cayman 
markdown: kramdown
plugins:
  - jekyll-seo-tag
